services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chocobar-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine3.21
    container_name: chocobar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chocobar-postgres
    ports:
      - '5432:5432'
    volumes:
      - chocobar-postgres-data:/var/lib/postgresql/data

volumes:
  chocobar-postgres-data:
